spring.application.name=SentiDiary

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.port=8088
server.servlet.context-path=/SentiDiary
server.servlet.session.timeout=3600

logging.level=debug
logging.level.deu.se.ood=debug

# JPA + MySQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/senti_diary?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=jdbctester
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#\uce74\uce74\uc624 \uc18c\uc15c \ub85c\uadf8\uc778
kakao.client-id=3b3bc4144ec5289cdb3fad778fb77b48
kakao.redirect-uri=http://localhost:8088/SentiDiary/kakao/callback

#jwt key
jwt.secret=mySuperSecretKeyForJwtToken123456
